import pandas as pd
import numpy as np
import astropy.units as u

def remake_rvfile(path, units, output_filename='output.rv', verbose=False):
    '''
    Create a streamlined RV file from a TRES or CHIRON data file generated by Lars Buchhave's TESS website.

    path: string containing the path to the source data file.
    units: astropy units of the input RVs.
    output_filename: string containing the name of the processed RV file. This can contain a path to a different directory.
    verbose: a boolean for whether or not to print the processed RV file.
    '''

    input_data = pd.read_csv(path, sep='\s+', header=0)

    vrad_units = np.array(input_data.vrad) * units
    svrad_units = np.array(input_data.svrad) * units
    
    data_new = pd.DataFrame({'Time (BJD)': input_data.BJD_UTC, 'RV (m/s)': vrad_units.to(u.m/u.s), 'RV error (m/s)': svrad_units.to(u.m/u.s)})

    with open(output_filename, 'w') as file:
        file.write('# Time (BJD), RV (m/s), RV error (m/s)\n')
        data_new.to_csv(file, sep=' ', index=False, header=False)

    if verbose==True:
        print('Processed file:\n', data_new)